---
services:
  freqtrade-h4:
    # image: freqtradeorg/freqtrade:stable
    image: freqtrade:henry    # Custom image: send a message to a group's topic.
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    # container_name: freqtrade-h4
    volumes:
      - "./user_data_h4:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    # ports:
      # - "8099:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SonicRStrategy

  freqtrade-daily:
    # image: freqtradeorg/freqtrade:stable
    image: freqtrade:henry
    restart: unless-stopped
    # container_name: freqtrade-daily
    volumes:
      - "./user_data_daily:/freqtrade/user_data"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy DailyCandleStrategy

  freqtrade-weekly:
    # image: freqtradeorg/freqtrade:stable
    image: freqtrade:henry
    restart: unless-stopped
    # container_name: freqtrade-weekly
    volumes:
      - "./user_data_weekly:/freqtrade/user_data"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy WeeklyCandleStrategy
